feat: any emoji render
revoltchat/rvmob pull request #24
Opened 2023-08-02 18:55 UTC by account0123

FastImage does not render svg file, then react-native-svg is imported.
`renderEmojis` function is called inside `spoilerRule` because if I create a new rule object there is a conflict.
### How renderEmojis work?
1. `renderEmojis` splits content by custom emoji regex
  i. Odd elements... are :ULID: then return as `CustomEmoji`
  ii. Even elements is splitted by default emoji regex (eg: `:smile:`) and mapped:
   - Odd elements are :name: then return as `SvgEmoji`
   - Even elements are strings

    iii. `subparts` flatmaps, each component is returned, each string is inspected for unicode characters search.

      1. If there are, characters are mapped as `SvgEmoji`, the array is interleaved with Text components and returns

    iv. Finally subparts (string|SvgEmoji array) is returned in `tokens` flat map.

2. At the end, elements can be a string array (no emojis found) or a string|Text|SvgEmoji|CustomEmoji array (at least one emoji found). 

## Please make sure to check the following tasks before opening and submitting a PR

* [X] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [X] I have tested my changes locally and they are working as intended
* [X] These changes do not have any notable side effects on other Revolt projects

2023-08-03 21:46 UTC, Rexogamer requested changes
Initial thoughts - I'll test this and clean up some other bits later, but let's start with these

2023-08-03 21:46 UTC, Rexogamer commented on src/lib/emojis.ts
> +  ...{
The built-in custom emoji are deprecated and will be removed in the new, official web client that will replace Revite - therefore, I'd recommend removing the list of them here/anything solely dedicated to supporting them

2023-08-03 21:46 UTC, Rexogamer commented on src/lib/utils.ts
> +  /*
We can probably just remove this instead of commenting it out

2023-08-03 21:46 UTC, Rexogamer commented on src/lib/emojis.ts
> +export const emojiDictionary = {
For this I was thinking of using [RevKit](https://github.com/Revolt-Unofficial-Clients/revkit), which comes with an emoji dictionary/various helper functions which can be found [here](https://github.com/Revolt-Unofficial-Clients/revkit/blob/master/core/src/utils/Emojis.ts) - this removes quite a bit of this burden from RVMob itself and places it on a community maintained and easily updatable package

2023-08-03 21:49 UTC, Rexogamer commented
One other thing that came to mind: while I'm happy to add support for the various packs (something Revkit also helps with), I also want to give the user the ability to use their system's emoji font so we might want to add a new setting for this and not render them if said setting = "system"

2023-08-04 00:02 UTC, account0123 commented on src/lib/emojis.ts
> +export const emojiDictionary = {
it is a good dependency indeed, i will give it a try

2023-08-06 06:56 UTC, Rexogamer commented
Something I've also noticed is that messages take a lot longer to render and the client seems to disconnect/break more (presumably due to the amount of images it has to fetch); however, I'm not 100% sure how we could realistically solve this unless we bundle every emoji SVG with the app :thinking:

2023-08-11 01:34 UTC, Rexogamer commented
(for external readers: we decided to comment out the built-in emoji renderer for now and just render custom emoji)

2023-08-11 10:13 UTC, Rexogamer approved these changes

2023-08-11 10:14 UTC, merged