Several quality-of-life UI improvements and misc changes
revoltchat/rvmob pull request #27
Opened 2023-08-15 14:09 UTC by alexispurslane

## Please make sure to check the following tasks before opening and submitting a PR

* [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [x] I have tested my changes locally and they are working as intended
* [x] These changes do not have any notable side effects on other Revolt projects

## Features

- Scroll to bottom on new messages (or when keyboard opens)
- Render messages from bottom to top like Discord
- Render channel header at the start of any channel or direct message (or saved notes), again ala Discord
- Add a UI setting for font size that changes the message font size and the message box font size (as well as adjusting the padding in various places to make this look nice)
- Reintroduce the AMOLED theme with some extra UI visual hints to make it more usable
- Remember the last server or direct message the user was in and restore them at startup. 
- Remember, for each server, the last channel in that server the user was in, and restore that channel when visiting that server (including on startup)

## Misc Changes
- Remove some dead code (including uncommented code that was nevertheless never used)
- Make Gradle build a full app and an F-Droid-compatible set of binaries.

2023-08-15 14:10 UTC, alexispurslane commented
For my next PR I'm going to try to make the process of restoring your chat location faster, by loading it with the UI instead of loading the UI and *then* changing the state *again*, I'm going to try to fix the message grouping by time, and I'm going to try to make messages just stay in frame without needing to auto scroll every time

2023-08-15 15:54 UTC, alexispurslane commented
Question: many of the components in this application currently are far too gigantic and mixed together in functionality to be manageable, it makes it very difficult to find where anything is done or make changes. Would you be open to accepting a pool request from me refactoring a lot of the gigantic 500 line components into subcomponents? Most of the sub components probably won't be reused in any way but I still think breaking it up and separating the concerns a little bit will make it more readable and easy to change.

2023-08-15 16:20 UTC, Rexogamer commented
I have been moving to refactor/split things more - I would prefer this be done somewhat gradually, but I would be open to PRs which help with this effort.

Now would also be a good time to mention that I've been moving to a new message view using a flat list instead (currently accessible via the Debug page on the DM list) - as such, while these changes are fine (incoming review comments aside), I wouldn't necessarily spend *too* much time on the current one at this point.

2023-08-15 18:02 UTC, alexispurslane commented
> I have been moving to refactor/split things more - I would prefer this be done somewhat gradually, but I would be open to PRs which help with this effort.

Sounds good, I'll see what I can do!



> Now would also be a good time to mention that I've been moving to a new message view using a flat list instead (currently accessible via the Debug page on the DM list) - as such, while these changes are fine (incoming review comments aside), I wouldn't necessarily spend _too_ much time on the current one at this point.

Got it. I actually almost switched to flatlist in my local codebase lol. I'll check it out and see how it feels.

2023-08-15 18:20 UTC, alexispurslane commented
ah well, looks like I'm not working on it today. Gradle is shitting itself even though I've changed nothing about my build environment so I can't get it to even build the app and i really don't feel like dealing with its bullshit (I spent six hours trying to get it to work the first time)

2023-08-15 20:50 UTC, Rexogamer commented
No rush - I'll test these changes locally and post some review comments soon, but you can take your time ^^

2023-08-19 10:57 UTC, Rexogamer requested changes
- Last channels feature works without any apparent issues
- Setting remarks LGTM/will be useful
- Mentions/size changing look fine minus the review comments

2023-08-19 10:57 UTC, Rexogamer commented on src/Generic.tsx
> +          "You'll have to restart the app after selecting a new theme for it to take effect.",
This technically isn't quite the case. You currently need to trigger a re-render, which you can do (for example) by switching channels - however, this is something I want to improve at some point

2023-08-19 10:57 UTC, Rexogamer commented on src/MessageBox.tsx
> +                : currentTheme.backgroundSecondary,
Just noting that I've made this a theme variable (`messageBoxInput`) - the duplication in the theme definitions is preferable as it's in one place, and we might want to tweak it for future themes

2023-08-19 10:57 UTC, Rexogamer commented on src/Generic.tsx
> +        default: '15',
This is a matter of personal taste and ultimately customisable so not a blocker but I would personally reduce this a bit, maybe to 10?

2023-08-19 10:57 UTC, Rexogamer commented on src/Generic.tsx
> +        default: '16',
ditto to 14, closer to the original size (less jarring for those upgrading)

2023-08-19 10:57 UTC, Rexogamer commented on src/MessageView.tsx
> +            this.scrollView.scrollToEnd({animated: false});
I can certainly see the value in this *but* I think there might be instances where you want to stay put (e.g. to keep a message in view while typing out a reply) - it might be worth only doing this if the user is near enough to the bottom? :thinking:

2023-08-19 10:57 UTC, Rexogamer commented on src/MessageView.tsx
> +              This is the start of your conversation.
I did want to add this but I was hoping to find a reliable method of checking if the user is at the first message in a channel before doing so so as not to mislead them - not sure if we should comment this out until then?

2023-08-19 20:26 UTC, alexispurslane commented on src/Generic.tsx
> +        default: '15',
Sorry, yeah 😅 I struggle with visual processing due to an injury and set all my font sizes huge. The one I actually use in the app is 18!

2023-08-19 20:29 UTC, alexispurslane commented on src/MessageView.tsx
> +              This is the start of your conversation.
Hmm. Having it is really nice for me for purely psychological reasons but it does make sense to comment it out for now. We really need a reliable way of figuring out if we are at the first and last messages — speaking of which, why don't the messages that come through from the request that we use to check if we're at the first message have IDs???

2023-08-19 20:29 UTC, alexispurslane commented
Okay in a few days when I'm feeling better I'll get on these changes. I also have some improvements I want to try to rhe last channel code

2023-08-19 21:27 UTC, Rexogamer commented on src/MessageView.tsx
> +              This is the start of your conversation.
That sounds odd - I haven't seen any instances of messages without IDs? `ReplyingMessage`s have the actual message object as a property, but those shouldn't be relevant here so 🤔

2023-08-21 13:31 UTC, alexispurslane commented on src/MessageView.tsx
> +              This is the start of your conversation.
I can't remember super clearly rn, but in the place where we request new messages for a channel, either the messages that are requested or the final message that's stored in the asynchronous storage object doesn't have an ID, which means it's not possible to tell whether the user has scrolled down to the very last message in the channel. Which is why I think you had setting the final message flag commented out

2023-08-21 15:19 UTC, Rexogamer commented on src/MessageView.tsx
> +              This is the start of your conversation.
I think that was written/commented out by Tai? Either way, when you can get the build to work I'd be grateful for any info you can find here

2023-08-22 18:43 UTC, alexispurslane commented
@Rexogamer I figured out what was wrong with atLatestMessages, the base message object was just being wrapped in order to add grouping information so I had to do `.message._id`. So I'm adding in the atLatestMessages logic to make scrolling down work. But I've noticed that since the new commits, `bottomOfPage` no longer works, which means a couple other scrolling related things (including my logic to make sure that if the user has manually scrolled up, that when a new message is added they don't get scrolled down, which is something you noticed) don't work now, so now I've got to track down that issue.

2023-08-22 20:31 UTC, alexispurslane commented
I've discovered that the scrolling forward functionality, now that I've gotten it to be called properly.... doesn't work. It produces this weird unholy mess where you have two interleaved copies of exactly the same messages when you scroll forward. It's weird. Trying to track down this bug now. Then I'll try to get on a reliable method of checking if you're at the first messages in a channel, because as it turns out we need this for scrolling up to work right at all for short channels.

2023-08-22 22:38 UTC, Rexogamer commented
I'm tempted to suggest splitting this PR up a bit - most of this (the last channel/server feature, the font size setting, the setting remarks, the Gradle tweaks, the design updates and the AMOLED re-enablement) could all be merged now, while the stuff that seems to be needing more investigation (I'm assuming just the scrolling changes?) could be split off into its own PR to not hold the rest of it up.

2023-08-22 22:48 UTC, alexispurslane commented
> I'm tempted to suggest splitting this PR up a bit - most of this (the last channel/server feature, the font size setting, the setting remarks, the Gradle tweaks, the design updates and the AMOLED re-enablement) could all be merged now, while the stuff that seems to be needing more investigation (I'm assuming just the scrolling changes?) could be split off into its own PR to not hold the rest of it up.

That's a good idea, it would just be a lot of work to do so, and I'm starting to despair of this entire project because I've spent about four hours today trying to get/keep the react native build system even working at all, and the app (with no changes on my end) has decided to completely stop running at all just recently, and nothing I can do seems to change it. Plus, I pulled your upstream changes, and there's several unhandled promise errors every few seconds and I can't get a stack trace on them that even ends anywhere in the code at all. I just really hate react native tbh. I'm usually far more productive than this but there's no room for me to be productive when I have to spend all day dealing with flimsy webdev bullshit (sorry for the cursing)

2023-08-22 22:56 UTC, alexispurslane commented
I hate this ******* piece of **** so much react native can suck my ****

2023-08-22 22:56 UTC, closed without merging

2023-08-22 23:23 UTC, Rexogamer commented
It's fine - I can create a new branch and revert any changes I would rather not merge. I'm slightly confused, however - I haven't seen any unusual errors on my end? React Native can be a pain, certainly